name: xylophone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audioplayers: ^0.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/1.mp3
    - assets/2.mp3
    - assets/3.mp3
    - assets/4.mp3
    - assets/5.mp3
    - assets/6.mp3
    - assets/7.mp3
    - assets/8.mp3
    - assets/9.mp3
    - assets/10.mp3
    - assets/11.mp3

